### ISSUE TITLE
SVD Issues 

### ISSUE THREAD

**Issue by sethchart** [learn-co-curriculum/dsc-collaborative-filtering-singular-value-decomposition#3]
Your dimensions are wrong for the SVD matrix decomposition. Orthogonal matrices are square so U and V need to be square matrices. Sigma handles the change in dimension. If A in n-by-d, then U is n-by-n Sigma is n-by-d and V is d-by-d.

**Comment by bpurdy-ds** [comment]
@sethchart is correct that we are incorrect. I'm fixing.

**Comment by bpurdy-ds** [comment]
Two ways to fix. Either leave the description of the matrices the same, and change the diagram OR leave the diagram as it is, and change the description of the matrices. I'll do the latter.

**Comment by bpurdy-ds** [comment]
Closed commit as described above: https://github.com/learn-co-curriculum/dsc-collaborative-filtering-singular-value-decomposition/issues/3#issue-746838515
